config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#login'
  root 'home#index'
  get 'analytics/followers'
  resources :admin_users, only: [:index]
  resources :reports, only: [:index]
  resources :tweets, only: [:index, :new, :create]
  resources :friendships, only: [:index] do
    collection do
      get :friends
      get :followers
      get :friends_and_followers
      get :friends_except_followers
      get :followers_except_friends
      post :follow
      post :unfollow
    end
  end
  resources :points, only: [:index]
  resources :daily_mission, only: [:index]
  resources :settings, only: [:index, :create]
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :admin_user

  def self.update_or_create(tweet)
    find_or_initialize_by(id: tweet.id).tap do |tweet_|
      tweet_.update!(
        tweeted_at: tweet.created_at,
        text: tweet.text,
        retweet_count: tweet.retweet_count,
        favorite_count: tweet.favorite_count
      )
    end
  end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  def index
    @tweets = current_user.tweets.order(tweeted_at: :desc)
  end

  def new
    @tweets = current_user.tweets.order(tweeted_at: :desc).limit(5)
  end

  def create
    tweet = Twitter::TweetService.call(current_user.client, params[:tweet_text])
    current_user.tweets.update_or_create(tweet)
    PointService.new(current_user, Point::TWEET).pay
    session[:tweet] = nil
    flash[:success] = 'ツイートしました。'
    redirect_to action: :new
  rescue StandardError
    flash[:danger] = 'ツイート失敗しました'
    session[:tweet] = params['tweet_text']
    redirect_to action: :new
  end
end

app/views/tweets/index.html.erb
<% content_for :page_title, 'ツイート一覧' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <table data-toggle="table" data-classes="table table-sm">
        <thead>
          <tr>
            <th scope="col" data-sortable="true">ツイート日</th>
            <th scope="col">ツイート内容</th>
            <th scope="col" data-sortable="true">RT数</th>
            <th scope="col" data-sortable="true">いいね数</th>
          </tr>
        </thead>
        <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td class="text-nowrap"><%= tweet.tweeted_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <td><%= tweet.text %></td>
              <td class="text-right"><%= tweet.retweet_count %></td>
              <td class="text-right"><%= tweet.favorite_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<% content_for :page_title, 'ツイート' %>
<div class="col-lg-6">
  <div class="card">
    <div class="card-body">
      <%= form_with url: tweets_path, local: true do |form| %>
        <p>
          <%= form.text_area :tweet_text, { value: session[:tweet], placeholder: 'いまどうしてる？', class: 'form-control' } %>
        </p>
        <p class="text-right mb-0"><%= form.submit 'ツイート', class: 'btn btn-info' %></p>
      <% end %>
      プレビュー
      <div class="row" style="max-width:618px">
        <div class="col-sm-1">
          <%= image_tag current_user.image_url, class: 'img-circle m-2', width: 49 %>
        </div>
        <div class="col-sm-11">
          <p class="mt-2 ml-3 mb-0"><b><%= current_user.name %></b> @<%= current_user.screen_name %></p>
          <p class="mt-0 ml-3" id="tweet-preview"><%= session[:tweet] %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">ツイートテンプレート</h3>
    </div>
    <div class="card-body">
      <p>
        <%= text_area_tag :tweet_text_template, cookies[:tweet_text_template], { placeholder: '#プロスピA', class: 'form-control' } %>
      </p>
      <p class="text-right mb-0">
        <%= button_tag '反映', class: 'btn btn-info', onclick: 'reflect_template()' %>
      </p>
      <hr>
      <div>Cookieにオートセーブされます。</div>
    </div>
  </div>
</div>
<div class="col-lg-6">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">直近5ツイート</h3>
    </div>
    <div class="card-body p-0">
      <table class="table">
        <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td><%= tweet.text %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
  document.forms[0].tweet_text.addEventListener("keyup", event => {
    let el = document.getElementById('tweet-preview');
    el.innerText = event.target.value;
  });

  document.getElementById('tweet_text_template').addEventListener("keyup", event => {
    document.cookie = 'tweet_text_template=' + encodeURIComponent(event.target.value);
  });

  const reflect_template = function() {
    document.forms[0].tweet_text.value = document.getElementById('tweet_text_template').value;
  }
</script>