config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#login'
  root 'home#index'
  get 'analytics/followers'
  resources :admin_users, only: [:index]
  resources :reports, only: [:index]
  resources :tweets, only: [:index, :new, :create]
  resources :friendships, only: [:index] do
    collection do
      get :friends
      get :followers
      get :friends_and_followers
      get :friends_except_followers
      get :followers_except_friends
      post :follow
      post :unfollow
    end
  end
  resources :points, only: [:index]
  resources :daily_mission, only: [:index]
  resources :settings, only: [:index, :create]
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  def index
    @friend_users = current_user.friends.includes(:twitter_user).order(created_at: :desc)
    @follower_users = current_user.followers.includes(:twitter_user).order(created_at: :desc)
    @friend_and_follower_users = @friend_users.where(twitter_user_id: @follower_users.map(&:twitter_user_id))
    @friend_except_follower_users = @friend_users.where.not(twitter_user_id: @follower_users.map(&:twitter_user_id))
    @follower_except_friend_users = @follower_users.where.not(twitter_user_id: @friend_users.map(&:twitter_user_id))
  end

  def friends
    @friends = current_user.friends.includes(:twitter_user).order(created_at: :desc)
  end

  def followers
    @followers = current_user.followers.includes(:twitter_user).order(created_at: :desc)
  end

  def friends_and_followers
    follower_ids = current_user.followers.select(:twitter_user_id)
    @friends_and_followers = current_user.friends
                                         .includes(:twitter_user)
                                         .where(twitter_user_id: follower_ids)
                                         .order(created_at: :desc)
  end

  def friends_except_followers
    follower_ids = current_user.followers.select(:twitter_user_id)
    @friends_except_followers = current_user.friends
                                            .includes(:twitter_user)
                                            .where.not(twitter_user_id: follower_ids)
                                            .order(created_at: :desc)
  end

  def followers_except_friends
    friends_ids = current_user.friends.select(:twitter_user_id)
    @followers_except_friends = current_user.followers
                                            .includes(:twitter_user)
                                            .where.not(twitter_user_id: friends_ids)
                                            .order(created_at: :desc)
  end

  def follow
    @point = Point::USER_FOLLOW
    point_service = PointService.new(current_user, Point::USER_FOLLOW)
    if point_service.pay
      @twitter_user_id = params[:twitter_id].to_i
      Twitter::FollowUserService.call(current_user.client, @twitter_user_id)
      current_user.friends.find_or_create_by(twitter_user_id: @twitter_user_id)
      @success = true
    else
      @success = false
    end
  end

  def unfollow
    @point = Point::USER_UNFOLLOW
    point_service = PointService.new(current_user, Point::USER_UNFOLLOW)
    if point_service.pay
      @twitter_user_id = params[:twitter_id].to_i
      Twitter::UnfollowUserService.call(current_user.client, @twitter_user_id)
      current_user.friends.find_by(twitter_user_id: @twitter_user_id).destroy
      @success = true
    else
      @success = false
    end
  end
end

app/views/friendships/_follower_user_table.html.erb
<table data-toggle="table" data-classes="table table-hover table-sm">
  <thead class="table-borderless">
    <tr>
      <th scope="col">ユーザー名</th>
      <th scope="col" data-sortable="true">ツイート数</th>
      <th scope="col" data-sortable="true">フォロー数</th>
      <th scope="col" data-sortable="true">フォロワー数</th>
      <th scope="col" data-sortable="true">FF比率</th>
      <th scope="col" data-sortable="true">いいね数</th>
      <th scope="col" data-sortable="true">リスト数</th>
      <th scope="col" data-sortable="true">フォローされた日</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.twitter_user.profile_image_url_https, class: 'img-circle mr-1' %>
          <%= user.twitter_user.name %> (<%= user.twitter_user.decorate.twitter_link %>)
        </td>
        <td class="text-right"><%= user.twitter_user.statuses_count %></td>
        <td class="text-right"><%= user.twitter_user.friends_count %></td>
        <td class="text-right"><%= user.twitter_user.followers_count %></td>
        <td class="text-right"><%= user.twitter_user.decorate.ff_ratio %></td>
        <td class="text-right"><%= user.twitter_user.favourites_count %></td>
        <td class="text-right"><%= user.twitter_user.listed_count %></td>
        <td class="text-right"><%= user.created_at.to_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friendships/_friend_user_table.html.erb
<table data-toggle="table" data-classes="table table-hover table-sm">
  <thead class="table-borderless">
    <tr>
      <th scope="col">ユーザー名</th>
      <th scope="col" data-sortable="true">ツイート数</th>
      <th scope="col" data-sortable="true">フォロー数</th>
      <th scope="col" data-sortable="true">フォロワー数</th>
      <th scope="col" data-sortable="true">FF比率</th>
      <th scope="col" data-sortable="true">いいね数</th>
      <th scope="col" data-sortable="true">リスト数</th>
      <th scope="col" data-sortable="true">フォローした日</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr id="twitter_user_id_<%= user.twitter_user.id %>">
        <td>
          <%= image_tag user.twitter_user.profile_image_url_https, class: 'img-circle mr-1' %>
          <%= user.twitter_user.name %> (<%= user.twitter_user.decorate.twitter_link %>)
        </td>
        <td class="text-right"><%= user.twitter_user.statuses_count %></td>
        <td class="text-right"><%= user.twitter_user.friends_count %></td>
        <td class="text-right"><%= user.twitter_user.followers_count %></td>
        <td class="text-right"><%= user.twitter_user.decorate.ff_ratio %></td>
        <td class="text-right"><%= user.twitter_user.favourites_count %></td>
        <td class="text-right"><%= user.twitter_user.listed_count %></td>
        <td class="text-right"><%= user.created_at.to_date %></td>
        <td class="text-right">
          <%= form_with url: unfollow_friendships_path, local: false do |form| %>
            <%= form.hidden_field :twitter_id, value: user.twitter_user.id %>
            <%= form.submit 'フォロー解除', class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friendships/_fun_user_table.html.erb
<table data-toggle="table" data-classes="table table-hover table-sm">
  <thead class="table-borderless">
    <tr>
      <th scope="col">ユーザー名</th>
      <th scope="col" data-sortable="true">ツイート数</th>
      <th scope="col" data-sortable="true">フォロー数</th>
      <th scope="col" data-sortable="true">フォロワー数</th>
      <th scope="col" data-sortable="true">FF比率</th>
      <th scope="col" data-sortable="true">いいね数</th>
      <th scope="col" data-sortable="true">リスト数</th>
      <th scope="col" data-sortable="true">フォローされた日</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr id="twitter_user_id_<%= user.twitter_user.id %>">
        <td>
          <%= image_tag user.twitter_user.profile_image_url_https, class: 'img-circle mr-1' %>
          <%= user.twitter_user.name %> (<%= user.twitter_user.decorate.twitter_link %>)
        </td>
        <td class="text-right"><%= user.twitter_user.statuses_count %></td>
        <td class="text-right"><%= user.twitter_user.friends_count %></td>
        <td class="text-right"><%= user.twitter_user.followers_count %></td>
        <td class="text-right"><%= user.twitter_user.decorate.ff_ratio %></td>
        <td class="text-right"><%= user.twitter_user.favourites_count %></td>
        <td class="text-right"><%= user.twitter_user.listed_count %></td>
        <td class="text-right"><%= user.created_at.to_date %></td>
        <td class="text-right">
          <%= form_with url: follow_friendships_path, local: false do |form| %>
            <%= form.hidden_field :twitter_id, value: user.twitter_user.id %>
            <%= form.submit 'フォロー', class: 'btn btn-info' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friendships/_user_table.html.erb
<table data-toggle="table" data-classes="table table-sm">
  <thead class="table-borderless">
    <tr>
      <th scope="col">ユーザー名</th>
      <th scope="col" data-sortable="true">ツイート数</th>
      <th scope="col" data-sortable="true">フォロー数</th>
      <th scope="col" data-sortable="true">フォロワー数</th>
      <th scope="col" data-sortable="true">FF比率</th>
      <th scope="col" data-sortable="true">いいね数</th>
      <th scope="col" data-sortable="true">リスト数</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.name %> (<%= user.twitter_link %>)</td>
        <td class="text-right"><%= user.statuses_count %></td>
        <td class="text-right"><%= user.friends_count %></td>
        <td class="text-right"><%= user.followers_count %></td>
        <td class="text-right"><%= user.ff_ratio %></td>
        <td class="text-right"><%= user.favourites_count %></td>
        <td class="text-right"><%= user.listed_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friendships/follow.js.erb
<% if @success %>
  document.getElementById('twitter_user_id_<%= @twitter_user_id %>').remove();
  document.querySelector('#friends_count').innerHTML = <%= current_user.friends_count %>;
  document.querySelector('#friends_and_followers_count').innerHTML = <%= current_user.friends_and_followers_count %>;
  document.querySelector('#follower_except_friend_users_count').innerHTML = <%= current_user.followers_except_friends_count %>;
  elm = document.querySelector('#user_point');
  elm.innerHTML = parseInt(elm.innerHTML) + <%= @point[:value] %>;
<% else %>
  alert('フォローに失敗しました。ポイントが不足している可能性があります。');
<% end %>

app/views/friendships/followers.html.erb
<% content_for :page_title, 'フォロワー' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <%= render partial: 'follower_user_table', locals: { users: @followers } %>
    </div>
  </div>
</div>

app/views/friendships/followers_except_friends.html.erb
<% content_for :page_title, '片思われ' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <%= render partial: 'fun_user_table', locals: { users: @followers_except_friends } %>
    </div>
  </div>
</div>

app/views/friendships/friends.html.erb
<% content_for :page_title, 'フォロー' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <%= render partial: 'friend_user_table', locals: { users: @friends } %>
    </div>
  </div>
</div>

app/views/friendships/friends_and_followers.html.erb
<% content_for :page_title, '相互フォロー' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <%= render partial: 'friend_user_table', locals: { users: @friends_and_followers } %>
    </div>
  </div>
</div>

app/views/friendships/friends_except_followers.html.erb
<% content_for :page_title, '片思い' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <%= render partial: 'friend_user_table', locals: { users: @friends_except_followers } %>
    </div>
  </div>
</div>

app/views/friendships/index.html.erb
<% content_for :page_title, 'ユーザー' %>
<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="friends-tab" data-toggle="tab" href="#friends" role="tab" aria-controls="friends" aria-selected="true">
            フォロー <span class="badge badge-secondary"><%= @friend_users.length %></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="followers-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="false">
            フォロワー <span class="badge badge-secondary"><%= @follower_users.length %></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="friend_and_follower_users-tab" data-toggle="tab" href="#friend_and_follower_users" role="tab" aria-controls="friend_and_follower_users" aria-selected="false">
            相互フォロー <span class="badge badge-secondary"><%= @friend_and_follower_users.length %></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="friend_except_follower_users-tab" data-toggle="tab" href="#friend_except_follower_users" role="tab" aria-controls="friend_except_follower_users" aria-selected="false">
            フォローされていない <span class="badge badge-secondary"><%= @friend_except_follower_users.length %></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="follower_except_friend_users-tab" data-toggle="tab" href="#follower_except_friend_users" role="tab" aria-controls="follower_except_friend_users" aria-selected="false">
            ファン <span class="badge badge-secondary"><%= @follower_except_friend_users.length %></span>
          </a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="friends" role="tabpanel" aria-labelledby="friends-tab">
          <%= render partial: 'friend_user_table', locals: { users: @friend_users } %>
        </div>
        <div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-tab">
          <%= render partial: 'follower_user_table', locals: { users: @follower_users } %>
        </div>
        <div class="tab-pane fade" id="friend_and_follower_users" role="tabpanel" aria-labelledby="friend_and_follower_users-tab">
          <%= render partial: 'friend_user_table', locals: { users: @friend_and_follower_users } %>
        </div>
        <div class="tab-pane fade" id="friend_except_follower_users" role="tabpanel" aria-labelledby="friend_except_follower_users-tab">
          <%= render partial: 'friend_user_table', locals: { users: @friend_except_follower_users } %>
        </div>
        <div class="tab-pane fade" id="follower_except_friend_users" role="tabpanel" aria-labelledby="follower_except_friend_users-tab">
          <%= render partial: 'fun_user_table', locals: { users: @follower_except_friend_users } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friendships/unfollow.js.erb
<% if @success %>
  document.getElementById('twitter_user_id_<%= @twitter_user_id %>').remove();
  document.querySelector('#friends_count').innerHTML = <%= current_user.friends_count %>;
  document.querySelector('#friends_and_followers_count').innerHTML = <%= current_user.friends_and_followers_count %>;
  document.querySelector('#friends_except_followers_count').innerHTML = <%= current_user.friends_except_followers_count %>;
  elm = document.querySelector('#user_point');
  elm.innerHTML = parseInt(elm.innerHTML) + <%= @point[:value] %>;
<% else %>
  alert('フォロー解除に失敗しました。ポイントが不足している可能性があります。');
<% end %>