config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#login'
  root 'home#index'
  get 'analytics/followers'
  resources :admin_users, only: [:index]
  resources :reports, only: [:index]
  resources :tweets, only: [:index, :new, :create]
  resources :friendships, only: [:index] do
    collection do
      get :friends
      get :followers
      get :friends_and_followers
      get :friends_except_followers
      get :followers_except_friends
      post :follow
      post :unfollow
    end
  end
  resources :points, only: [:index]
  resources :daily_mission, only: [:index]
  resources :settings, only: [:index, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MASAMUNE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Navbar -->
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">ホーム</a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <%= link_to points_path, class: 'nav-link', data: { turbolinks: false } do %>
              ポイント(<span id="user_point"><%= current_user.points.sum(:value) %></span>P)
            <% end %>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <%= link_to 'デイリーミッション', daily_mission_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <%= link_to '設定', settings_path, class: 'nav-link' %>
          </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
          <!-- Notifications Dropdown Menu -->
          <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
              <i class="fas fa-th-large"></i>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="/" class="brand-link">
          <%= image_tag 'AdminLTELogo.png', class: 'brand-image img-circle elevation-3', style: 'opacity: .8' %>
          <span class="brand-text font-weight-light">MASAMUNE</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar user panel (optional) -->
          <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
              <%= image_tag current_user.image_url, class: 'img-circle elevation-2', width: 35 %>
            </div>
            <div class="info">
              <a href="https://twitter.com/<%= current_user.screen_name %>" target="_blank" class="d-block">@<%= current_user.screen_name %></a>
            </div>
          </div>
          <!-- Sidebar Menu -->

          <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar nav-child-indent flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <!-- Add icons to the links using the .nav-icon class
                   with font-awesome or any other icon font library -->
              <li class="nav-item">
                <%= active_link_to '/', class: 'nav-link', wrap_class: 'nav-link', active: :exclusive do %>
                  <i class="fas fa-chart-line nav-icon"></i>
                  <p>ダッシュボード</p>
                <% end %>
              </li>
              <li class="nav-header">ツイート管理</li>
              <li class="nav-item">
                <%= active_link_to '/tweets/new', class: 'nav-link', wrap_class: 'nav-link' do %>
                  <i class="far fa-comment-alt nav-icon"></i>
                  <p>ツイート</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= active_link_to '/tweets', class: 'nav-link', wrap_class: 'nav-link', data: { turbolinks: false }, active: :exclusive do %>
                  <i class="far fa-comment-alt nav-icon"></i>
                  <p>ツイート一覧</p>
                <% end %>
              </li>
              <li class="nav-header">フォロー管理</li>
              <li class="nav-item">
                <%= active_link_to '/friendships/friends', class: 'nav-link', wrap_class: 'nav-link', data: { turbolinks: false } do %>
                  <i class="fas fa-user-friends nav-icon"></i>
                  <p>フォロー(<span id="friends_count"><%= current_user.friends_count %></span>)</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= active_link_to '/friendships/followers', class: 'nav-link', wrap_class: 'nav-link', data: { turbolinks: false } do %>
                  <i class="fas fa-user-friends nav-icon"></i>
                  <p>フォロワー(<span id="followers_count"><%= current_user.followers_count %></span>)</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= active_link_to '/friendships/friends_and_followers', class: 'nav-link', wrap_class: 'nav-link', data: { turbolinks: false } do %>
                  <i class="fas fa-user-friends nav-icon"></i>
                  <p>相互フォロー(<span id="friends_and_followers_count"><%= current_user.friends_and_followers_count %></span>)</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= active_link_to '/friendships/friends_except_followers', class: 'nav-link', wrap_class: 'nav-link', data: { turbolinks: false } do %>
                  <i class="fas fa-user-friends nav-icon"></i>
                  <p>片思い(<span id="friends_except_followers_count"><%= current_user.friends_except_followers_count %></span>)</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= active_link_to '/friendships/followers_except_friends', class: 'nav-link', wrap_class: 'nav-link', data: { turbolinks: false } do %>
                  <i class="fas fa-user-friends nav-icon"></i>
                  <p>片思われ(<span id="follower_except_friend_users_count"><%= current_user.followers_except_friends_count %></span>)</p>
                <% end %>
              </li>
              <li class="nav-header">分析</li>
              <li class="nav-item">
                <%= active_link_to '/reports', class: 'nav-link', wrap_class: 'nav-link' do %>
                  <i class="far fa-file nav-icon"></i>
                  <p>レポート</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= active_link_to '/analytics/followers', class: 'nav-link', wrap_class: 'nav-link' do %>
                  <i class="far fa-chart-bar nav-icon"></i>
                  <p>フォロワー分析</p>
                <% end %>
              </li>
              <li class="nav-header"></li>
              <li class="nav-item">
                <%= link_to logout_path, class: 'nav-link' do %>
                  <i class="fas fa-sign-out-alt nav-icon"></i>
                  <p>ログアウト</p>
                <% end %>
              </li>
            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <% flash.each do |type, message| %>
              <div class="alert alert-<%= type %> alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-check"></i><%= type.capitalize %>!</h5>
                <%= message %>
              </div>
            <% end %>
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark"><%= yield :page_title %></h1>
              </div><!-- /.col -->
              <% if yield(:page_title) != 'ダッシュボード' %>
                <div class="col-sm-6">
                  <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">ホーム</a></li>
                    <li class="breadcrumb-item active"><%= yield :page_title %></li>
                  </ol>
                </div><!-- /.col -->
              <% end %>
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <div class="content">
          <div class="container-fluid">
            <div class="row">
              <%= yield %>
            </div>
            <!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <div class="p-3">
          <h5>Title</h5>
          <p>Sidebar content</p>
        </div>
      </aside>
      <!-- /.control-sidebar -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
          <%= link_to 'https://github.com/ytkg/masamune', target: '_blank' do %>
            <i class="fab fa-github"></i>
          <% end %>
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; <%= Time.zone.now.year %> <a href="/">MASAMUNE</a>.</strong> All rights reserved.
      </footer>
    </div>
    <!-- ./wrapper -->
  </body>
</html>